<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TcXunit.Parser\TcXunit.Parser.csproj" />
    <ProjectReference Include="..\TcXunit.Runner\TcXunit.Runner.csproj" />
  </ItemGroup>

</Project>
